version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8876:80
    depends_on:
      - backend
    container_name: budget_nginx

  backend:
    build:
      context: .
      dockerfile: _docker/backend/Dockerfile
    volumes:
      - ./:/var/www
    container_name: budget_backend
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    
    environment:
        POSTGRES_DB: budget
        POSTGRES_PASSWORD: root
    ports:
      - 5432:3306
    container_name: budget_db
   
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

